### ISSUE TITLE
Description lengths in publiccode.yml

### ISSUE THREAD

**Issue by bfabio** [Amsterdam/signals-frontend#1742]
**Describe the bug**
The lengths of description keys does not respect [the standard](https://docs.italia.it/italia/developers-italia/publiccodeyml-en/en/master/schema.core.html#section-description):

```
publiccode.yml:22:5: description.nl.shortDescription: must be less or equal than 150
publiccode.yml:24:5: description.nl.longDescription: must be more or equal than 500
```

If you find it useful, there's a GitHub Action you can use to automatically check the well-formedness of `publiccode.yml`: https://github.com/italia/publiccode-parser-action :slightly_smiling_face:

**Comment by bartjkdp** [comment]
Some suggestions based on the text of Signalen.org:

**Short**
```
Signalen is een open source proces- en taaksysteem voor overheden, dat meldingen over de openbare ruimte automatisch categoriseert en routeert```

**Long**
```
Signalen is een proces- en taaksysteem, ontwikkeld op initiatief van de gemeente Amsterdam voor het effectiever en klantvriendelijker afhandelen van meldingen over de openbare ruimte.

Amsterdam krijgt per jaar zo’n 300.000 meldingen over de openbare ruimte te verwerken. Van huisraad bij de vuilnisbak tot en met verlaten sloepjes in de gracht. Ruim 1.400 ambtenaren werken 24/7 met het afhandelen van meldingen in Signalen. Sinds de invoering van Signalen is de klanttevredenheid over de afhandeling van meldingen in Amsterdam met ruim 30 procent gestegen.

De Signalen software is open source ontwikkeld en kan vrij gebruikt worden door andere overheden en gemeenten.
```

**Comment by MauritsR** [comment]
@bartjkdp Your suggestion sounds good - will create a PR for it

**Comment by MauritsR** [comment]
@bfabio First time I see it, but apparently the publiccode yaml is validated by VSCode! Should we hit a validation issue again we'll probably introduce the GitHub Action you linked. 
![vs-code-publiccode](https://user-images.githubusercontent.com/10672773/126467555-23930bd3-775d-442a-ab2b-2a441827510d.png)

**Comment by bfabio** [comment]
@MauritsR I noticed it yesterday as well with vim + coc.vim + language servers, and I was pleasantly surprised but puzzled where it came from! :slightly_smiling_face: 

I think it uses https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/publiccode.json
